parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
<<<<<<< HEAD
    env(DATABASE_URL): 'mysql://root@127.0.0.1:8889/nao-appli'
=======
    env(DATABASE_URL): 'mysql://root@127.0.0.1:3306/nao-app'
>>>>>>> 15bd4a56fa07dcf3c75bed10e4453a6d5bca8332

doctrine:
    dbal:
        # configure these for your database server
<<<<<<< HEAD
        dbname: nao-appli
=======
        dbname: nao-app
>>>>>>> 15bd4a56fa07dcf3c75bed10e4453a6d5bca8332
        host:   localhost
        user:   root
        driver: pdo_mysql
        server_version: '5.7'
        charset: utf8
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            engine: InnoDB


        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
