web_profiler:
    toolbar: true
    intercept_redirects: true
#    excluded_ajax_paths:  ^/((index|app(_[\w]+)?)\.php/)?_wdt

#    excluded_ajax_paths:  ^/((index|app(_[\w]+)?)\.php/)?_wdt
framework:
    profiler: { only_exceptions: false }
